# fly.toml app configuration file
app = 'ospd-mail-client-hw1'
primary_region = 'ewr'  # Newark (closest to NYC)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  GEMINI_DB_PATH = "/data/conversations.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[[mounts]]
  source = "ospd_data"
  destination = "/data"
