"""Auto-generated HTTP client for Mail Client Service API.

This package contains the code generated by openapi-python-client
from the Mail Client Service OpenAPI specification.
"""

from .mail_client_service_api_client.client import Client
from .mail_client_service_api_client.models.message_response import MessageResponse

__all__ = ["Client", "MessageResponse"]
